package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestScanExtractsStatusFromLeadingComment(t *testing.T) {
	dir := t.TempDir()
	files := map[string]string{
		"treasurer.md": "<!-- Status: designed -->\n<!-- Council-2026-04-16: created from merger -->\n# Treasurer\n",
		"ceo.md":       "<!-- Status: retired -->\n# CEO\n",
		"builder.md":   "<!-- Status: running -->\n# Builder\n",
	}
	for name, body := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0644); err != nil {
			t.Fatal(err)
		}
	}

	entries, err := scan(dir)
	if err != nil {
		t.Fatalf("scan: %v", err)
	}
	if len(entries) != 3 {
		t.Fatalf("len(entries) = %d, want 3", len(entries))
	}
	// Sorted alphabetically by name.
	if entries[0].Name != "builder" || entries[0].Status != "running" {
		t.Errorf("entries[0] = %+v, want {builder, running}", entries[0])
	}
	if entries[1].Name != "ceo" || entries[1].Status != "retired" {
		t.Errorf("entries[1] = %+v, want {ceo, retired}", entries[1])
	}
	if entries[2].Name != "treasurer" || entries[2].Status != "designed" {
		t.Errorf("entries[2] = %+v, want {treasurer, designed}", entries[2])
	}
}

func TestScanSkipsFilesWithoutStatusComment(t *testing.T) {
	dir := t.TempDir()
	files := map[string]string{
		"treasurer.md": "<!-- Status: designed -->\n# Treasurer\n",
		"CONTEXT.md":   "# Shared Context\n\nNo status comment here.\n",
		"README.md":    "# Readme\n",
	}
	for name, body := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0644); err != nil {
			t.Fatal(err)
		}
	}

	entries, err := scan(dir)
	if err != nil {
		t.Fatalf("scan: %v", err)
	}
	if len(entries) != 1 {
		t.Fatalf("len(entries) = %d, want 1 (CONTEXT.md and README.md should be skipped)", len(entries))
	}
	if entries[0].Name != "treasurer" {
		t.Errorf("entries[0].Name = %q, want treasurer", entries[0].Name)
	}
}

func TestScanMissingDirHintsAtSubmoduleInit(t *testing.T) {
	_, err := scan("/nonexistent/hive/agents")
	if err == nil {
		t.Fatal("want error for missing dir")
	}
	if !strings.Contains(err.Error(), "git submodule update") {
		t.Errorf("error should hint at submodule init; got: %v", err)
	}
}

func TestRenderProducesDeterministicOutput(t *testing.T) {
	entries := []entry{
		{Name: "advocate", Status: "running"},
		{Name: "treasurer", Status: "designed"},
	}
	got, err := render(entries)
	if err != nil {
		t.Fatal(err)
	}
	want := `// Code generated by gen-persona-status; DO NOT EDIT.

package personas

// HiveStatus maps persona name → hive-declared lifecycle status.
// Source: third_party/hive/agents/<name>.md <!-- Status: X -->
var HiveStatus = map[string]string{
	"advocate":  "running",
	"treasurer": "designed",
}
`
	if string(got) != want {
		t.Errorf("render mismatch.\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}
